# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.9
python: 3.9

# Install the codecov pip dependency
install:
  - pip install pytest-cov
  - pip install codecov

# Run the pytest test
script:
  - pytest --cov=./ --cov-report=xml
  - bash <(curl https://codecov.io/bash)

# Push the results back to codecov
after_success:
  - codecov